apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: cracks
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: container
      MaxScale: 5
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  environment:
    name: ""
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: ""
      namespace: ""
  podspec:
    containers:
    - image: registry.sachasmart.com/pavement_cracks:amd-v7 # TODO
      imagePullPolicy: IfNotPresent
      name: cracks
      ports:
      - containerPort: 8000
        name: http-env
      resources: {}
      env:
      # - name: ENV
      #   value: "debug"
      - name: ALLOWED_ORIGINS
        value: "*"
    imagePullSecrets:
      - name: registry-secret
    terminationGracePeriodSeconds: 0
  resources: {}