_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.9.7
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 13
                - 14
                - 19
                - 23
                - 47
                - 55
            "4": 3.9.7
            "5": 0.19.3
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
train:
    value:
        agnostic_nms: false
        amp: true
        augment: false
        auto_augment: randaugment
        batch: 16
        bgr: 0
        box: 0.05
        cache: true
        cfg: null
        classes: null
        close_mosaic: 10
        cls: 0.3
        conf: null
        copy_paste: 0.1
        copy_paste_mode: flip
        cos_lr: false
        crop_fraction: 1
        data: data.segmentation.yaml
        degrees: 0
        deterministic: true
        device: 0
        dfl: 1.5
        dnn: false
        dropout: 0
        dynamic: false
        embed: null
        epochs: 150
        erasing: 0.4
        exist_ok: true
        fliplr: 0.5
        flipud: 0
        format: torchscript
        fraction: 1
        freeze: null
        half: false
        hsv_h: 0.015
        hsv_s: 0.7
        hsv_v: 0.4
        imgsz: 640
        int8: false
        iou: 0.2
        keras: false
        kobj: 0.7
        line_width: null
        lr0: 0.01
        lrf: 0.1
        mask_ratio: 4
        max_det: 300
        mixup: 0.1
        mode: train
        model: ./yolo11m-seg.pt
        momentum: 0.937
        mosaic: 1
        multi_scale: false
        name: exp1
        nbs: 64
        nms: false
        opset: null
        optimize: false
        optimizer: auto
        overlap_mask: true
        patience: 100
        perspective: 0
        plots: true
        pose: 12
        pretrained: true
        profile: false
        project: runs/train
        rect: false
        resume: false
        retina_masks: false
        save: true
        save_conf: false
        save_crop: false
        save_dir: runs/train/exp1
        save_frames: false
        save_hybrid: false
        save_json: false
        save_period: -1
        save_txt: false
        scale: 0.9
        seed: 0
        shear: 0
        show: false
        show_boxes: true
        show_conf: true
        show_labels: true
        simplify: true
        single_cls: false
        source: null
        split: val
        stream_buffer: false
        task: segment
        time: null
        tracker: botsort.yaml
        translate: 0.1
        val: true
        verbose: true
        vid_stride: 1
        visualize: false
        warmup_bias_lr: 0
        warmup_epochs: 3
        warmup_momentum: 0.8
        weight_decay: 0.0005
        workers: 8
        workspace: null
