apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: pavement-cracks
data:
  nginx.conf: |
    worker_processes auto;

    events {
        worker_connections 1024;
    }

    http {
        sendfile on;
        log_format custom_format '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $body_bytes_sent '
        '"$http_referer" "$http_user_agent" '
        '$upstream_response_time';

        server { 
            listen 8080;
            server_name prometheus;

            location = /metrics {
                stub_status;
            }
        }

        server {
            listen 80;
            server_name truenas;
            access_log /var/log/nginx/access.log custom_format;
            error_log /var/log/nginx/error.log;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            location / {
                resolver 192.168.2.111;
                rewrite ^/+(.*)$ /pavement-cracks-static-site-bucket/index.html last;
            }

            location /pavement-cracks-static-site-bucket/ {
                proxy_set_header Host 192.168.2.5:9000;
                proxy_pass http://192.168.2.5:9000/pavement-cracks-static-site-bucket/;
            }

            location ~* \.(js|css|png|jpg|jpeg|gif|ico|woff|woff2|ttf|svg|eot)$ {
                try_files $uri @minio_assets;
            }

            location @minio_assets {
                resolver 192.168.2.111;
                proxy_set_header Host 192.168.2.5:9000;
                proxy_pass http://192.168.2.5:9000/pavement-cracks-static-site-bucket$uri;
            }
        }
    }





